#!/bin/sh


if [ -z "$1" ]; then
    echo "Usage: `basename "$0"` CONTAINER [COMMAND [ARG]...]"
    echo ""
    echo "Enters the Docker CONTAINER and executes the specified COMMAND."
    echo "If COMMAND is not specified, runs an interactive shell in CONTAINER."
else
    PID=$(docker inspect --format "{{.State.Pid}}" "$1")
    CONTAINER=$1
    [ -z "$PID" ] && exit 1
    shift

    # env is to clear all host environment variables and set then anew
    if [ $# -lt 1 ]; then
        # No arguments, default to `su` which executes the default login shell
        docker exec -it $CONTAINER script -q -c "TERM=xterm /bin/bash" /dev/null
    else
        # Has command
        # "$@" is magic in bash, and needs to be in the invocation
        docker exec -it $CONTAINER script -q -c "/bin/bash -c \"$@\"" /dev/null
    fi
fi

